#! /usr/bin/env python

import pyfits
from ogip_dictionary import ogip_dictionary
from ogip_spectral_check import *

if __name__== "__main__":
    import argparse
    from ogip_dictionary import ogip_dictionary
    import sys
    parser = argparse.ArgumentParser()
    parser.add_argument("input", type=str, help="Input file to test")
    parser.add_argument('-l', "--logfile", type=argparse.FileType('w'),default = sys.stdout)
    parser.add_argument("-v", "--verbosity", action="count", default=0)
    args = parser.parse_args()
    if "/" in args.input:
        filename=args.input[args.input.rfind("/"):]
    else:
        filename=args.input
    REPORT = ogip_spectral_check(args.input)
