#! /usr/bin/env python 

#
# Note that the -W is required in order to avoid python's warnings
# module from supressing repeated messages, which we would actually
# want to see from possibly the same wrong keywords in different files
# or exensions...
#


from ogip_check import ogip_check

if __name__== "__main__":
    import argparse
    import sys
    parser = argparse.ArgumentParser()
    parser.add_argument("input", type=str, help="Input file to test")
    parser.add_argument('-t','--type', type=str, help="Type:  one of TIMING, SPECTRAL, CALDB, ARF, RMF",default=None)
    parser.add_argument('-l', "--logfile", type=argparse.FileType('w'),default = sys.stdout)
    parser.add_argument("-v", "--verbosity", action="count", default=0)
    args = parser.parse_args()
    status= ogip_check(args.input,args.type,args.logfile,args.verbosity)
    exit(status.status)

