#! /usr/bin/env python -W all::UserWarning:

#
# Note that the -W is required in order to avoid python's warnings
# module from supressing repeated messages, which we would actually
# want to see from possibly the same wrong keywords in different files
# or exensions...
#

from ogip_check_dir import ogip_check_dir

if __name__== "__main__":
    import argparse
    import sys
    parser = argparse.ArgumentParser()
    parser.add_argument("basedir", type=str, help="Input base directory to test")
    parser.add_argument("logdir", type=str, help="Output directory to write logs to, one per tested file")
    parser.add_argument("-v", "--verbosity", action="count", default=0)

    parser.add_argument("--ignore_dir",type=str,help="Comma-separated list of directory names to ignore;  default none.",default='')
    parser.add_argument("--default_type",type=str,help="Default type to check for unrecognized files;  default 'none'.",default='none')
    parser.add_argument("--ignore_suffix",type=str,help="Comma-separated list of file suffixes to ignore;  default=.jpg,.txt,.gif,.dat,.ps,.html,.par,.PNG,.PDF,.HTM",default='.jpg,.txt,.gif,.dat,.ps,.html,.par,.PNG,.PDF,.HTM')

    args = parser.parse_args()

    slist= args.ignore_suffix.split(',') 
    slist=slist+[x+'.gz' for x in slist]
    ignore={
        'suffixes':tuple(slist),
        'directories':tuple(args.ignore_dir.split(',')),
    }
    status=ogip_check_dir(args.basedir,args.logdir,ignore,args.default_type,args.verbosity)
    exit(status)
