#! /usr/bin/env python

import pyfits
from ogip.ogip_check import ogip_check

if __name__== "__main__":
    import argparse
    import sys
    parser = argparse.ArgumentParser()
    parser.add_argument("input", type=str, help="Input file to test")
    parser.add_argument('-t','--type', type=str, help="Type:  one of TIMING, SPECTRAL, CALDB, ARF, RMF",default=None)
    parser.add_argument('-l', "--logfile", type=argparse.FileType('w'),default = sys.stdout)
    parser.add_argument("-v", "--verbosity", action="count", default=0)
    args = parser.parse_args()
    status= ogip_check(args)
    exit(status.status)

